[package]
name = "digita"
version = "0.1.0"
description = "DiGitA local Git workspace"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
git-presence = { path = "../crates/git-presence" }
keyring = { version = "3", features = ["apple-native", "windows-native", "sync-secret-service", "crypto-rust"] }
